# Generated by Django 3.2.3 on 2021-07-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_question_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontag',
            name='slug',
            field=models.SlugField(default='', max_length=350),
            preserve_default=False,
        ),
    ]
