# Generated by Django 3.2.3 on 2021-07-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_questiontag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='questiontag',
            name='slug',
            field=models.SlugField(blank=True, max_length=350, null=True),
        ),
    ]
